### ISSUE TITLE
Ability to close the Flight Sim Tracker taskbar plugin

### ISSUE THREAD

**Issue by thestonefox** [nguyenquyhy/Flight-Tracker-StreamDeck#104]
Right now there is no way of closing the taskbar companion app without going into task manager and finding the process and terminating.

It would be nice to have an option on the taskbar icon to exit the app, then a shortcut to turn it back on if needbe.

**Comment by nguyenquyhy** [comment]
The behavior you see is actually due to the current Stream Deck plugin design from Elgato: the plugin is started and stopped automatically with the Stream Deck software. If you look around, you'll see the process from the background process of other plugin as well.
![image](https://user-images.githubusercontent.com/1560418/102751545-f3dc5c00-43a2-11eb-8697-427695d4e697.png)

A bit more details of this: when Stream Deck software is started, it passes a bunch of parameters to the plugin. Those parameters are needed for the communication between Stream Deck and the plugin. If you exit the plugin manually (e.g. with Task Manager), there is no way to properly restart it other than restarting Stream Deck software.

However, if you simply concern about having fewer icon in the system tray, I have some discussion before about whether to hide the icon or not (the process will still run regardless). My personal preference is to be transparent on what is running by always showing the icon, but I would understand if others don't want to clutter the system tray. I am thinking of having a setting for that, but right now I am not sure what is the proper implementation of plugin's (instead of button's) settings in Stream Deck.

**Comment by thestonefox** [comment]
Yeah I can see what you mean. I've had something crash with the streamdeck plugin and ended up with multiple task icons for the flight tracker, but I bet if another streamdeck plugin crashes and reloads then you'd end up with multiple hidden processes too.

I agree that it's best to have the running app visible rather than a hidden process.

**Comment by DominikSerafin** [comment]
> My personal preference is to be transparent on what is running by always showing the icon

@nguyenquyhy, considering that other Stream Deck plugins processes don't show up in tray, I think not showing Flight Tracker icon there would be reasonable.

Otherwise, I'd love the ability to hide it (maybe via right click context menu on tray icon or as a separate .streamDeckPlugin installation file).
