### ISSUE TITLE
Feature request: Hold Buttons

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#12]
The `Generic Toggle Button` is great for 90% of what I want to do, but I have a few buttons that I want to be able to "hold down" and have the event repeat. For example, I use the `MIXTURE_INCR` and `MIXTURE_DECR` events to lean/rich the mixture in my aircraft.

Using the Generic Toggle Button without a feedback or display value works fine, as long as you keep tapping the button. I would like the event to continue triggering when the button is held down.

I believe this is similar to the current examples components, eg: `AP Heading Increase` , but there is no generic version of that layout.

**Comment by nguyenquyhy** [comment]
We observed a small complication with that during Alpha stage: if you send too many events to SimConnect (from the holding), SimConnect encountered some internal issue and you will need to close Stream Deck for a couple of seconds before restarting to be able to connect again.
That's why when holding heading, it repeats +/-1 event only a couple of times and then uses another event to directly perform +/-10 to reduce the rate.

I do plan to merge the 2 designs to allow the generic button to have such feature, but it will take a little bit of time.

**Comment by rmroc451** [comment]
@nguyenquyhy I was thinking, there could be a button type that sets a bool for + or - on the static deck logic class and then all the updated buttons could use that to increment or decrement when quick press or press and hold. Seems pretty straightforward and keeps the other button logic pretty simple. Thoughts?

**Comment by nguyenquyhy** [comment]
Yes, I agree, and I'll build a generic up/down button. 

But due to the issue with repeating event, we need separate events for short hold & long hold. 
For long hold, there are actually 2 ways to set a value in SimConnect:
- A set event
- Send the variable with a value (reversed direction of getting variable)
Neither way works universally though, so some experiments are needed for each.

In short, I don't think the complication of this is code-wise, but because I am trying to not over-complicate the user setup experience while maintaining a certain level of stability.

**Comment by rmroc451** [comment]
@nguyenquyhy yeah. You could save the cumulative long hold to a variable and then on key up do the set of the final value, while updating the image text with the variable value every few tick cycles.  That would eliminate the barrage to simconnect.

**Comment by nguyenquyhy** [comment]
Released in v0.30
