### ISSUE TITLE
Prop and mixture 

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#145]
Hello, 

Its possible we can get a mixture and propeller mixture 

hold Button 100 percent Inc and dec 

and short hold the same now working 

I fly the b36 and Start the enigne and Batterie i need 100 percent and i parking on the Gate its 0 percent 

I want to get a Button or hold Button for full 100 percent 

Thx a lot

**Comment by sn3akz** [comment]
> propeller mixture

I reckon you mean prop pitch?

These things are normally bound to an axes. Since it's not trivial to set values, I think this is not the desired way to use the Stream Deck.

However, you should be able to use the vars `THROTTLE_INCR` and `THROTTLE_DECR` to create your own buttons :)

**Comment by nguyenquyhy** [comment]
As Pieter said those variables are not usually set by buttons, so I'll close this for now. However, once we roll out support for triggering any events outside of our list, you can use button with *_SET events for this purpose. Providing the correct parameter is tricky though because there are some mapping involved.
