### ISSUE TITLE
Garmin1000 Audio panel issue

### ISSUE THREAD

**Issue by pjglewis** [nguyenquyhy/Flight-Tracker-StreamDeck#208]
Stream Deck 4.9.3.132222 - MSFS Updated/up to date this am (not sure what version that makes it)

This is my query from yesterday on Flightsim.to -
![Capture 4](https://user-images.githubusercontent.com/80406959/110647596-dbb0f780-81af-11eb-8919-ccdcf525f00b.PNG)

The events that I am trying to map to the stream deck are -
![Capture 3](https://user-images.githubusercontent.com/80406959/110647793-1155e080-81b0-11eb-9b31-15e4a9d8efd1.PNG)

For some reason I have had no issues with the PFD and MFD ones, but none of these mid panel ones will activate the buttons e.g.
![Capture 1](https://user-images.githubusercontent.com/80406959/110648242-71e51d80-81b0-11eb-850c-d1b0fc4c432d.PNG)
![Capture 2](https://user-images.githubusercontent.com/80406959/110648329-86291a80-81b0-11eb-8c3c-74448f4c6d86.PNG)

I am not focused on the feedback values at the moment (so please ignore the one shown in capture 2 as it is simply WIP), I am just trying to get the buttons to push.

This is the Baron G58 profile (including Garmin1000). To get the softkey menus working there are several nested profiles. G58 at the top, Garmin1000 underneath and PFD and MFD underneath that etc. (hopefully that isn't too confusing).
[Garmin1000.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6116850/Garmin1000.zip)

The events are in the Mobiflight file in my community folder (as are all the others), and they are correct according to the developer mode of MSFS too. I can't see what I am doing wrong.

You may notice a few issues with feedback values outside in that I can't find values for -
Cowl flaps %
Prop sync
windshield de-ice - can't find the toggle or the event
Although I have yet to check MSFS developer mode and I may be able to add these through Mobiflight

Also I have a very odd issue with TOGGLE_CABIN_LIGHTS (and LIGHT_CABIN), in that the lights turn on in the sim but the button in MSFS does not move!
Thanks for any help you are able to offer
Regards
Peter

**Comment by pjglewis** [comment]
If you do take a look at the profiles please bare in mind that it is WIP - and don't judge some of the aesthetics too harshly! Also, the Garmin softkey menus were modelled on the real thing, so some of the PFD menu options don't actually appear in MSFS. I was planning to take them out as necessary (and had started cutting branches already from the MFD 'tree'. :)

**Comment by rmroc451** [comment]
@pjglewis I might get around to looking at some of this today/tonight.  I hadn't any luck with the mobiflight audio panel toggles so far, but maybe that has changed since the last sim update (and I grabbed an updated version of the mobiflight wasm module too).

I had been using: 
`COM1_TRANSMIT_SELECT` to toggle w/ `COM_TRANSMIT__1` for feedback
`COM2_TRANSMIT_SELECT` to toggle w/ `COM_TRANSMIT__2` for feedback
`COM_RECEIVE_ALL_TOGGLE` to toggle w/ `COM_RECEIVE_ALL` for feedback

That was limping me by (there are other updates on my screenshot that are in the pipe for this weekends release, if we can get them merged up):
![image](https://user-images.githubusercontent.com/15070945/111430673-b00aa180-86c8-11eb-815b-c9e7c5b75a12.png)

**Comment by nguyenquyhy** [comment]
I'm not very well versed in MobiFlight, but right now the plugin does not impose any limit on events, I would assume this is fixed or something is wrong with the events.txt mapping. Please feel free to reopen otherwise.
