### ISSUE TITLE
Custom true/false icons don't save with profile

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#23]
Unlike other images, the true/false icons don't save with the profile - so sharing a custom profile just reverts to the defaults again.

Is it possible to (a) bake the image data directly into the profile save, or
(b) document where the images should be stored relative to the profile to still be accessed (rather than absolute paths)?

**Comment by nguyenquyhy** [comment]
(a) I have already done some work with embed, and it seems to work quite well. However, I'll take more time to polish the interface to make sure it is not too complicated. Also have to double check if there is any size limit on the settings of each button.
(b) The profile is stored in %appdata%\Elgato\StreamDeck\ProfilesV2, so doing relative path would require user to manually find the correct profile folder (because the folder name is a GUID), and then copy the image folder in. I am not too fond of adding manual steps though. One solution I can think of for this would be a global setting for image folder, and the profile will contains relative path from that image folder.

**Comment by nguyenquyhy** [comment]
This is now implemented in v0.23 with the Embed button.
