### ISSUE TITLE
SEATBELT SWITCH

### ISSUE THREAD

**Issue by Kaledozor** [nguyenquyhy/Flight-Tracker-StreamDeck#274]
Thank you very much for this new version, sacred work!
The TOGGLE are finally working !!
But a question about return values:

TOGGLE EVENT: MOBIFLIGHT_SEATBELT_SWITCH
FEEDBACK VALUE: CABIN SEATBELTS ALERT SWITCH (not working).

Are there any new return values with MOBIFLIGHT?

_Originally posted by @Kaledozor in https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/issues/265#issuecomment-870059294_

**Comment by nguyenquyhy** [comment]
There is, but it uses a different mechanism to return the value than what is being implemented in the plugin. 

Honestly I am a bit hesitant to implement support for that as I am concerned about the impact to the sim. Currently the plugin requests a set of variables (everything in a Stream Deck page) when you switch to a particular page/folder, and SimConnect efficiently sends back all the values every frame. SimConnect is robust enough so that there is no impact to frame rate or crashes in the sim.

At least I would wait a bit for all the workaround to get L-VARs to settle down, or even better if Microsoft/Asobo releases an official way to request L-VARs instead of having to require another mod for this.

Also, I really don't understand why FBW chooses to be very incompatible to SimConnect.

**Comment by Kaledozor** [comment]
Thank you for your accompaniement.
We will wait for things to evolve, especially for FBW.
Too bad, because sometimes when we find solutions following an update we go back to the start.

**Comment by nguyenquyhy** [comment]
Closing this as duplicated of https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/issues/218.
