### ISSUE TITLE
Generic Toggle with Keyboard Input and SimConnect Feedback Value

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#30]
Not sure if this is possible, but I ran across an instance for selecting the AP Nav Freq (1 or 2) where there does not appear to be a toggle value available, but there is a feedback sim variable for what is selected.  So I guess it would be good to have a new type of button that sends a keyboard hotkey while also using a simulation variable for the feedback value.  But the usefulness of this might be limited. It would only be helpful in situations where there is no toggle value, but a keyboard binding exists, and where a feedback value is available from the Sim.

**Comment by nguyenquyhy** [comment]
I thought about this before but there are some downsides to keyboard shortcuts:
- Keyboard shortcuts only works when the sim is in focus. I actually does a lot in my second screen (e.g. checking maps, charts and even non-sim related stuff during long flight). So having buttons with keyboard shortcut would create some inconsistent  experience comparing to currently when the buttons work all the time (unless then there is a bug 😂). It's even worse if whatever active software actually recognizes that keyboard shortcut and does something crazy.
- As you said, it would only be helpful when there is no toggle value but keyboard binding. However, I believe this is simply due to the lack of documentation at the moment, so this scenario will only get smaller over time.

So probably I wouldn't prioritize this unless there are some crucial functions that many need right away.

By the way, what is this "selecting the AP Nav Freq (1 or 2)" you mentioned about?

**Comment by Virtual-Chris** [comment]
That makes sense. 

I believe the Nav 1/2 toggle switches the source of the AP Nav mode between the two nav radio sources.  The keyboard binding is under Autopilot > SET AUTOPILOT NAV SELECT  and the description for the control says "Set the nav (1 or 2) which is used by the Nav hold mode"

**Comment by Virtual-Chris** [comment]
ps. Are any of the Garmin 1000 buttons available via SimConnect?  I hate trying to turn the knobs with my mouse.  It would be ideal if we could map some of those buttons to the Stream Deck.

**Comment by nguyenquyhy** [comment]
There are a bunch of G1000 events from FSX time, which is also marked as Recognized in latest MSFS SimConnect docs. You can check out the current supporting one in our Struct.cs.

**Comment by Virtual-Chris** [comment]
> There are a bunch of G1000 events from FSX time, which is also marked as Recognized in latest MSFS SimConnect docs. You can check out the current supporting one in our Struct.cs.

I cannot get any of the G1000 events to trigger using a Generic Toggle Button.  Any idea why that might be?

**Comment by nguyenquyhy** [comment]
I have added AP_NAV_SELECT_SET with parameter 1 or 2 to switch between NAV1/2 (tracked in #47).
The G1000 buttons are tracked in #36, so I'll close this one for now.
