### ISSUE TITLE
Parking Brake A320NX

### ISSUE THREAD

**Issue by Kaledozor** [nguyenquyhy/Flight-Tracker-StreamDeck#321]
I can no longer find a return value on the PARKING BRAKE of the 320NX.
The **BRAKE_PARKING_INDICATOR** value has not worked for several months.
However on my Honeycom Bravo the light turns on correctly with this value: **A32NX_PARK_BRAKE_LEVER_POS == 1**

Is there something that I am doing wrong or not understanding?

**Comment by nguyenquyhy** [comment]
I think A32NX_PARK_BRAKE_LEVER_POS is a L_VAR, which needs some module installed to extract. 

The plugin works via SimConnect, which is a common interface for all aircraft, so it can receive only SimVar such as `BRAKE PARKING INDICATOR`. The one you mentioned is the correct variable, so the problem is on the aircraft itself. https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimVars%2FAircraft_SimVars%2FAircraft_Brake_Landing_Gear_Variables.htm
