### ISSUE TITLE
H-JET and Autopilot

### ISSUE THREAD

**Issue by juyttewaal** [nguyenquyhy/Flight-Tracker-StreamDeck#349]
It looks like some of the auto-pilot functions from the streamdeck profile don't work with the new H-Jet. Still doing some testing though.
Thank you - JU

**Comment by matiaslarson** [comment]
All the default buttons have been working on my Honeycomb Bravo so I don’t think they’re using custom values for anything but the vnav. That one will require MobiFlight to access.

**Comment by matslarson** [comment]
All the default buttons have been working on my Honeycomb Bravo so I don’t think they’re using custom values for anything but the vnav. That one will require MobiFlight to access.

**Comment by nguyenquyhy** [comment]
I'll close this for now. If it still happens, please provide more specific information on what is not working.

However, if the issue happens only on the H-Jet, it is most likely because the aircraft dev chooses to ignore SimConnect event. I cannot really fix that. You can try to use MobiFlight to create custom mapping if you have the internal event.
