### ISSUE TITLE
pls give the command in Sep variable 

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nguyenquyhy** [comment]
I have no clue what SimConnect event can be used for this. Any idea?

**Comment by rug4ever** [comment]
you have on your screen on flightsim site the Button with this command. its possible you give me the keybind for this?

**Comment by nguyenquyhy** [comment]
Yeah I know the in-sep switch, but I am not sure what you are talking about here. The plugin works with only SimConnect Events instead of keybinds, and I have no idea what SimConnect event is for that function.

**Comment by rug4ever** [comment]
> Yeah I know the in-sep switch, but I am not sure what you are talking about here. The plugin works with only SimConnect Events instead of keybinds, and I have no idea what SimConnect event is for that function.

hello,

oh Sorry

I dont know the keybind for this Button and dont find that in msfs2020 Control kevbinds. i hope you can me say where i can find the keybind Button or so you Know how can i find the keybind in msfs2020

**Comment by nguyenquyhy** [comment]
Oh I have no idea either 😂. I remembered it was tied to some de-icying buttons, but they changed that or something.

**Comment by Crunchmeister1** [comment]
It already "works" in the sense that the toggle variable for Inertial Separator is ANTI_ICE_TOGGLE_ENG1, and the feedback value is ENG ANTI ICE:1. I have it in the my current TBM panel. 

What doesn't work is that it's instantaneous vs slowly ramping up and down over a 30 second period. When you activate it, you get an instant torque loss, and when turning it off, you get an instant torque spike. I suspect that the panel switch in game does exactly that - it ramps the in-sep up from 0 to 100% and back down over a 30 sec period. That's why this command doesn't visually activate the switch in the plane. The ideal would be if they exposed that switch via SimConnect.    

This only works in the TBM. I don't know what the in-sep command is in the C208. That command doesn't work for it.

**Comment by sn3akz** [comment]
> I dont know the keybind for this Button

G :)
And indeed it is bound to anti ice buttons.

**Comment by Crunchmeister1** [comment]
> but dont see change the button in the machine
Like I said in my post, it doesn't toggle the button on the plane's panel in game. I suspect Asobo programmed that button custom to include the 30 second ramp-up / ramp down timer. UItimately, it engages the anti-ice, but it's not a direct connection between that button and the user. That button is neither exposed through the SDK nor is it available in game to bind a key to.

**Comment by nguyenquyhy** [comment]
Close this for now since it will need some design change in the way Asobo use SimConnect event in default aircraft, which I don't think would happen soon.
