### ISSUE TITLE
A320neo no com input

### ISSUE THREAD

**Issue by xpulz** [nguyenquyhy/Flight-Tracker-StreamDeck#68]
Below are some useful information that you can include to help with troubleshooting the issue:
- Stream Deck Plugin and MSFS version
- Description of the issue & expected behavior
- Steps to reproduce the issue
- If the issue happens consistently, an export of your profile would help tremendously.
- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`
- Screenshots

**Comment by xpulz** [comment]
hi,
I just tried the streamdeck app (starting with the com). When I try to use the com button I see the correct com freq on the button. However the input doesn't work (enter / xfer / ...). I did the test with the flybywire A320 dev version.

**Comment by sn3akz** [comment]
The COM system on the A320 does not adhere to the default SimConnect system. Not much we can about it right now :(

**Comment by nguyenquyhy** [comment]
It's not really SimConnect issue. If you check the ATC panel, you should see that the frequency from the Stream Deck plugin is set correctly in game.
![image](https://user-images.githubusercontent.com/1560418/100387052-055f6c00-3062-11eb-8c8b-c9def0dbd3b5.png)

The problem is the aircraft itself doesn't react to SimConnect change. It displays a separate value and set to SimConnect when you change the value in the flight deck (so a one-way thing). This is actually a bug of both the default A320 and the A32NX.
