### ISSUE TITLE
Values with index numbers don't report correctly

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#8]
I entered feedback value of `GENERAL ENG MASTER ALTERNATOR:1`, and similar, and anything with an index in it doesn't seem to report correctly.

Similarly, when dealing with gauges, anything with an index doesn't work. For example, `GENERAL ENG MIXTURE LEVER POSITION:1`

**Comment by nguyenquyhy** [comment]
Due to some complication in interfacing with SimConnect, you cannot actually set any SimConnect variables in the generic buttons. The variable has to exist in https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/v0.2/FlightStreamDeck.Core/Structs.cs.

I have updated the requested variables in version 0.2 of the plugin at https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/releases.
